### ISSUE TITLE
No background for highlighted code

### ISSUE THREAD

**Issue by constgen** [frontarm/mdx-util#53]
I use Webpack 3, so have to use `mdx-loader@2.2.1`

I followed the instructions about importing a theme https://github.com/frontarm/mdx-util/tree/master/packages/mdx-loader#syntax-highlighting . But the result is that background styles are not applied because the generated markup doesn't preserve theme selectors https://github.com/PrismJS/prism/blob/master/themes/prism-tomorrow.css#L39

```css
:not(pre) > code[class*="language-"],
pre[class*="language-"] {
	background: #2d2d2d;
}
```

_Built result_

![image](https://user-images.githubusercontent.com/673144/61185532-45879f80-a663-11e9-86a2-0c0d9eb2b35b.png)
